// Generated by scripts/generate.py — do not edit by hand.

module;

#include <collab/detail/identifier.decls.hpp>

export module collab:identifier;

export namespace collab {
    using ::collab::identifier;
}
