// Generated by scripts/generate.py — do not edit by hand.

module;

#include <collab/detail/manifest.decls.hpp>

export module collab:manifest;

export namespace collab {
    using ::collab::manifest;
}
